### ISSUE TITLE
how to make custom methods for the resources?

### ISSUE THREAD

**Issue by mgenev** [florianholzapfel/express-restify-mongoose#122]
I'm not seeing in the docs, once I've auto-created the crud, what is a good pattern for attaching custom methods to these resources?

**Comment by Zertz** [comment]
There is nothing built in at the moment.

What I do with the Express 4 Router is mount the API where I want it: `app.use('/api/v1', apiRouter);`

Then in my restify files I do this:

```javascript
router.get('/events/:id/awesome, function(req, res, next) {
  ...
});

restify.serve(router, models.Event, {
  ...
});
```

Although, yes, it would be neat to be able to extend the routes. Something along those lines:

```javascript
restify.serve(router, models.Event, {
  extend: {
    get: {
      awesome: function(req, res, next, result) {
        // Equivalent to router.get('/events/:id/awesome)
        // result would be a document
      }
    }
  }
});
```

**Of course, this is only an example and isn't implemented!**

**Comment by Zertz** [comment]
@florianholzapfel Do you think this is relevant and, if so, any ideas on how to go with it?

**Comment by florianholzapfel** [comment]
Actually, I am also using the router object for this. I think it is the most flexible solution.

In my opinion, allowing to make custom methods using this library would make it too complex.

**Comment by Zertz** [comment]
Good point, I suppose it would be tough to cover everyone's use cases.

However, it would be *really* convenient if the module (optionally) caught routes starting with rather than an exact match, like `/api/v1/entity/:id*`. Then, it could store the result in the `req` object and call next.

Makes sense?

**Comment by mgenev** [comment]
Since I opened this issue I remade my server with koa actually and i'm using a similar module koa-mongo-rest

and I solved the custom method issue with this code:
https://github.com/mgenev/nautilus/blob/master/server%2Fconfig%2Fkoa.js#L30-L69

**Comment by florianholzapfel** [comment]
@mgenev thanks for sharing this implementation.

@Zertz I think we could return a router object that maps to ```/api/v1/entity/```. This would allow something like this:

```
restify.serve(router, models.Event)
   .get(':id/awesome', function(req, res, next) { ... })
   .get('somethingelse', function(req, res, next) { ... });
```

This solution would give the user some flexibility over the routes whilst not adding much complexity to the library. What do you think?

**Comment by Zertz** [comment]
@florianholzapfel Looks good, definitely in the spirit of Express.

For consistency, it should map to `/api/v1/entity` (without the trailing slash).

1. `/count` and `/shallow` would have to be treated as special cases
2. Unless I'm mistaken, the feature would be restricted to Express >= 4
3. For clarity, the `app` variable should be renamed to `router`

Per your example:
```javascript
restify.serve(router, models.Event)
   .get('/:id/awesome', function(req, res, next) { ... })
   .get('/something', function(req, res, next) { ... });
```

`/something` doesn't really make sense because it would be caught by the lib as the `:id` parameter. `/:id/awesome` is the interesting feature here. Now that I think of it, the lib shouldn't populate the model because the use case for those deep routes often perform some sort of aggregate or require access to private fields.

All in all, a very simple change for a good bit of convenience! If you haven't started already, I can get this done today or tomorrow.

**Comment by florianholzapfel** [comment]
added in #129
