### ISSUE TITLE
Undefined behavior when URL has a trailing slash

### ISSUE THREAD

**Issue by Zertz** [florianholzapfel/express-restify-mongoose#159]
Express ignores it if strict routing is off (default):
```
GET /api/Customers/ === GET /api/Customers
```

Restify default to Express' equivalent of strict routing, assumes that the trailing slash implies an undefined id parameter:
```
GET /api/Customers/ === GET /api/Customers/:id (where id === undefined)
```

I've [created some tests](https://github.com/florianholzapfel/express-restify-mongoose/commit/2dbf94d6a704d3c24576424ddbd01f4f2ac1c7c4), but they're skipped for now until we decide on the proper behavior.

Ideas?

**Comment by Zertz** [comment]
@florianholzapfel Do you think we should strip the trailing slash internally or leave it as is let the user and his framework handle this?

**Comment by florianholzapfel** [comment]
i think we should not remove the trailing slash, because we don't have any possibility to know the callers intent. it would be better to return an error in this case.

e.g.: ```GET /api/Customers?select=name``` should return all customers name fields vs ```GET /api/Customers/:id?select=name``` should return the customers name field whose id matches ```:id```. If ```:id``` is undefined and we strip the trailing slash, it would return all customers name fields.
