### ISSUE TITLE
query nested document

### ISSUE THREAD

**Issue by ricoud** [florianholzapfel/express-restify-mongoose#300]
when querying
`competition?populate=league&sort=league&limit=10&skip=0&query={"competitionName":"Free%20Ladder"}`
I got following answer
`[{"_id":"57b75fc635889902164d4ec2","competitionName":"Free Ladder","nbMatchs":2,"league":{"_id":"57b75fc635889902164d4ec1","leagueName":"Cabalvision Official League","__v":0},"__v":0}]`

Then trying following query
`competition?populate=league&sort=league&limit=10&skip=0&query={"league.leagueName":"Cabalvision%20Official%20League"}`
and receive empty array

"express-restify-mongoose": "^4.1.1"
"mongoose": "^4.5.9"

Thanks

**Comment by Zertz** [comment]
What's happening here is that by using `"league.leagueName"`, MongoDB looks for an object nested inside the actual document, ie.:

```js
{
  "league": {
    "leagueName": "Cabalvision Official League"
  }
}
```

However, since MongoDB by itself doesn't support joins your document probably looks something like the following, it can't find your document because `"league.leagueName"` indeed does not exist.

```js
{
  "league": ObjectId("...")
}
```

Luckily, mongoose supports a form of join, which actually runs a second query, but the query syntax is slightly different. You need to move your query into the populate option, like this:

```
populate: {
  "path": "league",
  "match": {
    "leagueName": "Cabalvision Official League"
  }
}
```

Let me know if that helps :)

**Comment by ricoud** [comment]
Thanks for the reply.  
Unfortunately I wasn't able to make it work. Coming from sql world, it's hard to change to MongoDB and nosql mindset. Anyway, I directly include the league data, including competition, as subdocument of my main collection (game).  
Search queries with regex on different fields are then easy to perform, even if from a perfomance point of view it is certainly not the best choice.  
Thanks again.
