### ISSUE TITLE
[Question] Is there a client side query builder?

### ISSUE THREAD

**Issue by kjanoudi** [florianholzapfel/express-restify-mongoose#303]
I'm wondering if there's a pattern that this module uses to parse it's queries which may make it easier to use that pattern to build queries client side. In an angular or react application, I'd love to be able to extract the query building to its own package, so I'm wondering if this has been done before or if someone can guide me to the logic to get it started myself?

**Comment by Zertz** [comment]
I haven't finished my coffeer yet so I'm not exactly sure i understand what you mean so bear with me!

We don't really parse queries, most of them are passed straight to mongoose, so that particular query object wouldn't be all that useful client side since they only support Node. The only thing mongoose can do on the browser is schema validation.

All we do internally is relatively simple, we iterate the query, select, populate and so on to make sure the filter allows you do use the fields the user is trying to refer to. Otherwise, querying the database is all done by mongoose.

**Comment by kjanoudi** [comment]
@Zertz ah that was my question, in a very roundabout fashion, is what you do with the query string passed in through the URL. Thanks

**Comment by Zertz** [comment]
Yeah, we don't do much parsing at all. Some options like `populate` are normalized so we always pass the array form (`[{ "path": "hello" }]`) to mongoose, but that's about it. Everything else is either `parseInt()` or `JSON.parse` with some error handling. Then we validate according to your options like `limit`, `private` and so on.

As for building query objects, they're just objects so it's pretty straightforward. You can build a query string like this and append the result to the URL

```
JSON.stringify({
  query: {
    name: "Zertz"
  }
})

// https://api.example.org/v1/people?query={"name":"Zertz"}
```
