### ISSUE TITLE
Dynamic models

### ISSUE THREAD

**Issue by slasktrat** [florianholzapfel/express-restify-mongoose#325]
I was just about to ask for possibility to support dynamic models (/connections) and found that @peek4y actually implemented [just this](https://github.com/peek4y/express-restify-mongoose/commit/d6ec1d87c3598797f4021f96ab5de8d771979e12) (yesterday!). 

I've tested it and it works like a charm. 
Would this be accepted in case of a PR?

**Comment by peek4y** [comment]
Hey @slasktrat ! Glad my changes worked out for you. I'd be happy to send out a PR. I was earlier in a hurry, and wasn't sure about a PR, so I published a scoped package.

**Comment by slasktrat** [comment]
@peek4y Is this published as a scoped package with public access? I get "no such package available : @peek4y/express-restify-mongoose"

**Comment by peek4y** [comment]
yes it is [public](https://www.npmjs.com/package/@peek4y/express-restify-mongoose), I'm able to install. Are you able to access the npm link?

**Comment by slasktrat** [comment]
Sorry, my fault! I'm going through a sinopia proxy and it seems that sinopia does not proxy scoped packages by default. Got it now :)

**Comment by peek4y** [comment]
Ah! :) Cool.

**Comment by slasktrat** [comment]
For info, I don't use the modelFactory.getModel callback, but instead injecting/replacing erm.model in a preMiddleware as I need the request context in place.

**Comment by peek4y** [comment]
Ah I see, got it. Probably I can include that, to the `getModel` param list, what else do you require apart from the request context (req object)?

**Comment by Zertz** [comment]
There has been a lot of refactoring done in an upcoming PR, so while I'm willing to look into getting your idea merged, it will most likely need some work before it can be merged in the new code base.

**Comment by Zertz** [comment]
@peek4y Would you like to PR your changes?

**Comment by peek4y** [comment]
@Zertz  Hey Zertz, absolutely. It's been a while I made any changes to my fork, will update and send out a PR soon.

**Comment by peek4y** [comment]
@Zertz https://github.com/florianholzapfel/express-restify-mongoose/pull/351 here it is!

**Comment by webberwang** [comment]
The dynamic model only supports modifying the current model. Is it possible to do something like so...

```typescript
const models = fetchExternalData();

for (model in models) {
  restify.serve(
    router,
    mongoose.model(
      model.name,
      new mongoose.Schema(model.schema),
    ),
  )
}
```

**Comment by OliverFischer** [comment]
@peek4y Hey peek4y it is a long time since you contributed this feature, but in absence of any documentation concerning dynamic models, here is my understanding of the functionality: 

I can hook into the resolving of a model which will be placed in the req.erm object by providing a modelFactory in the options object when i initially call restify.serve. If the object `modelFactory` containing a function `getModel` is present in options, each time a request enters express, the middleware calls this function to retrieve some kind of 'multi-tenant' model. If this is correct, I can dynamically resolve the multi-tenant model by providing my implementation of `getModel`. 

The implementation in express-restify-mongoose is:
```
app.use((req, res, next) => {
    const getModel = options.modelFactory && options.modelFactory.getModel

    req.erm = {
      model: typeof getModel === 'function' ? getModel() : model,
    }

    next()
  })
```
But I do not understand how the implementation of such a function could resolve a 'custom' model to return if `getModel()`is called without any scope/information concerning the current request? If the request would be passed to the function someone can inspect the url/referrer to return a suitable model. Please give me some advice on properly implementing a model factory.

**Comment by Zertz** [comment]
If this is still a problem, please open a new issue.
