### ISSUE TITLE
Make options.outputFn() asynchronous

### ISSUE THREAD

**Issue by b-gran** [florianholzapfel/express-restify-mongoose#327]
Right now, `options.outputFn()` is called synchronously and then `options.postProcess()` is called asynchronously [immediately afterward](https://github.com/florianholzapfel/express-restifymongoose/blob/master/src/middleware/prepareOutput.js#L55). 

If both of these hooks were to make asynchronous resource calls, the execution order would be unpredictable.

If we make `outputFn()` asynchronous, we can ensure `outputFn()` finishes before calling `postProcess()`. 

For backwards compatibility, we can perform a check on `outputFn()` to call it synchronously.

Since this is backwards compatible, I went ahead and integrated it into #314 [here](https://github.com/florianholzapfel/express-restify-mongoose/pull/314/commits/6e70102e01e149a9a0dac71c02d38f77053d2bd0)

Since `outputFn()` can now be asynchronous, it can also (safely) generate errors. Right now, they're getting passed to `onError()`. There are tests for that behavior. If anyone has different ideas about how to handle those errors, let me know.

**Comment by Zertz** [comment]
This behavior is documented and my opinion here is that as little as possible should be done in `outputFn`. That said, I'm fine with making it optionally async, though I don't think passing errors to `onError` makes sense since the library's work is done at that point and there isn't much we can do about it. I'm thinking these errors should be forwarded to the user, using the traditional `next(err)` pattern. For consistency, we need to make sure `postProcess` is not called  an error happens in `outputFn`.
